import './globals.css';
import AppContextProvider from '@/context/AppContext';

export const metadata = {
  title: 'Integrated',
  description: 'Generated by Integrated',
  icons: {
    icon: '/favicon.jpg'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#0f101b] scroll-smooth">
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
}
