import { Inter } from 'next/font/google';
import './globals.css';
import AppContextProvider from '@/context/AppContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Integrated',
  description: 'Generated by Integrated'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black scroll-smooth">
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
}
